In [99]:
import numpy as np

In [112]:
# 1번
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [101]:
# 2번
np.eye(1,10,k=4)

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [102]:
# 3번
o = np.arange(10,50)
o

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [103]:
# 4번
o[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [104]:
# 5번
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
# 6번
test = np.array([1,2,0,0,4,0], float)
test[test != 0]

array([1., 2., 4.])

In [106]:
# 7번
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [107]:
# 8번
a = np.random.uniform(0,1,9).reshape(3,3)
a

array([[0.6979251 , 0.39820488, 0.88312219],
       [0.18100751, 0.43249917, 0.0181432 ],
       [0.69143786, 0.46969065, 0.12822219]])

In [108]:
# 9번
np.max(a)

0.8831221914041427

In [109]:
np.min(a)

0.018143202754672627

In [110]:
# 10번
a.mean(axis=1)

array([0.65975073, 0.21054996, 0.42978357])

In [111]:
a.mean(axis=0)

array([0.52345682, 0.4334649 , 0.34316253])